name: nakamerch
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  crypto: ^3.0.3
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gambar/
    - assets/ikon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
